### ISSUE TITLE
Remote test failure on prod

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#33]
Pulled the SMTP code and email verification is working well. However, remote submission caused this error: 

```
(2017-09-05 14:44:12; grader.py:72) DEBUG:AutoGrade.grader: Running student tests in: uploads/submission/student_2/assignment_1/2017-09-05-144412_submission/
(2017-09-05 14:44:12; grader.py:79) DEBUG:AutoGrade.grader: Capturing stdout
(2017-09-05 14:44:12; grader.py:85) DEBUG:AutoGrade.grader: Starting test process for submission
(2017-09-05 14:44:12; grader.py:48) DEBUG:AutoGrade.grader: Changing directory ...
(2017-09-05 14:44:12; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/api/submit_assignment
Traceback (most recent call last):
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/views.py", line 291, in api
    score, outlog = run_student_tests(extract_directory, assignment.total_points, assignment.timeout)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/grader.py", line 86, in run_student_tests
    p.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 127, in __init__
    sys.stdout.flush()
ValueError: I/O operation on closed file
(2017-09-05 14:44:12; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/api/submit_assignment
Traceback (most recent call last):
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/views.py", line 291, in api
    score, outlog = run_student_tests(extract_directory, assignment.total_points, assignment.timeout)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/grader.py", line 86, in run_student_tests
    p.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 127, in __init__
    sys.stdout.flush()
ValueError: I/O operation on closed file
(2017-09-05 14:44:12; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/api/submit_assignment
Traceback (most recent call last):
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/views.py", line 291, in api
    score, outlog = run_student_tests(extract_directory, assignment.total_points, assignment.timeout)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/grader.py", line 86, in run_student_tests
    p.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 127, in __init__
    sys.stdout.flush()
ValueError: I/O operation on closed file
(2017-09-05 14:44:12; basehttp.py:124) ERROR:django.server: "POST /autograde/api/submit_assignment HTTP/1.1" 500 91233
(2017-09-05 14:44:12; basehttp.py:124) ERROR:django.server: "POST /autograde/api/submit_assignment HTTP/1.1" 500 91233
(2017-09-05 14:44:12; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/api/submit_assignment
Traceback (most recent call last):
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/views.py", line 291, in api
    score, outlog = run_student_tests(extract_directory, assignment.total_points, assignment.timeout)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/grader.py", line 100, in run_student_tests
    res_line = out.splitlines()[-1]
IndexError: list index out of range
(2017-09-05 14:44:12; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/api/submit_assignment
Traceback (most recent call last):
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/views.py", line 291, in api
    score, outlog = run_student_tests(extract_directory, assignment.total_points, assignment.timeout)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/grader.py", line 100, in run_student_tests
    res_line = out.splitlines()[-1]
IndexError: list index out of range
(2017-09-05 14:44:12; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/api/submit_assignment
Traceback (most recent call last):
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/views.py", line 291, in api
    score, outlog = run_student_tests(extract_directory, assignment.total_points, assignment.timeout)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/grader.py", line 100, in run_student_tests
    res_line = out.splitlines()[-1]
IndexError: list index out of range
(2017-09-05 14:44:12; basehttp.py:124) ERROR:django.server: "POST /autograde/api/submit_assignment HTTP/1.1" 500 83851
(2017-09-05 14:44:12; basehttp.py:124) ERROR:django.server: "POST /autograde/api/submit_assignment HTTP/1.1" 500 83851
(2017-09-05 14:44:12; basehttp.py:78) INFO:django.server: - Broken pipe from ('121.52.146.103', 53516)

(2017-09-05 14:44:12; basehttp.py:78) INFO:django.server: - Broken pipe from ('121.52.146.103', 53516)
```

And the `test-results.log` file in submission directory for this submission is completely empty.

**Comment by recluze** [comment]
My fix does not work on the server. Can we easily get rid of the multiprocessing and just call the run_test function? 

(I wrote to master directly since a PR would have produced the same effect.)

**Comment by recluze** [comment]
I'm getting this between "Chaning directory" and "IO Error": 

```
(2017-09-05 16:24:29; grader.py:48) DEBUG:AutoGrade.grader: Changing directory ...
usage: manage.py [options] [file_or_dir] [file_or_dir] [...]
manage.py: error: unrecognized arguments: --timeout=3
  inifile: None
  rootdir: /home/sys-autograder/autograder/AutoGrader/uploads/submission/student_2/assignment_1/2017-09-05-162429_submission
(2017-09-05 16:24:29; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/api/submit_assignment
```

Looks like the process is trying to run manage.py instead of pytest. Might have to do something with the fact that we're on Gentoo in prod.

**Comment by recluze** [comment]
So, this is solved. After about 3 hours of debugging and hopelessness, it turns out that if you don't have the pytest-timeout plugin installed, it basically forks the main process instead of calling pytest's main function!! 

So, the solution was simply `pip install pytest-timeout` on prod. 

We should probably list all needed packages in `requirements.txt`
