### ISSUE TITLE
View assignment file on assignment_report page broken

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#80]
After the security fix, the backend `View` button for `assignment_report` also returns no assignment code.

**Comment by soachishti** [comment]
Working fine with me.

Screenshot: https://www.screencast.com/t/Gdblvo7M3Eof

**Comment by recluze** [comment]
Does it show the submission when you click on "View"? Also, try on prod.

**Comment by recluze** [comment]
Here's the log: 

```
Traceback (most recent call last):
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sys-autograder/autograder/AutoGrader/AutoGrade/views.py", line 181, in download
    submission = Submission.objects.get(id=submission_id, student__user=request.user)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sys-autograder/autograder/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Submission matching query does not exist.
(2017-10-05 16:59:33; exception.py:135) ERROR:django.request: Internal Server Error: /autograde/download/
```

**Comment by recluze** [comment]
Looks like we need to put a check for superuser in there.
